# Generated by Django 4.2.7 on 2023-12-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(default='Uttara', max_length=50)),
                ('motherName', models.CharField(default='rokeya begum', max_length=20)),
            ],
        ),
    ]
