# Generated by Django 4.2.7 on 2024-01-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('bPrice', models.IntegerField()),
                ('category', models.CharField(choices=[('Horror', 'Horror'), ('Fiction', 'Fiction'), ('Novel', 'Novel'), ('Fantasy', 'Fantasy'), ('Story', 'Story')], max_length=15)),
                ('userReview', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='myUser', to=settings.AUTH_USER_MODEL)),
                ('userReview', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
