# Generated by Django 4.2.7 on 2024-01-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
