# Generated by Django 4.2.7 on 2024-01-12 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_image_alter_usermodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='userReview',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='userReview',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
