# Generated by Django 4.2.7 on 2024-01-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_userreview_alter_usermodel_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='userReview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
