# Generated by Django 4.2.7 on 2024-01-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowedbook_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
