# Generated by Django 4.2.7 on 2024-01-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrowedbook_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
