# Generated by Django 5.0 on 2024-01-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0003_alter_carmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carList.carmodel'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
