# Generated by Django 5.0 on 2024-01-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0004_remove_carmodel_brand_brand_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='cars',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carList.brand'),
        ),
    ]
