# Generated by Django 4.2.7 on 2024-01-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0006_comment_carmodel_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carList.carmodel'),
        ),
    ]
