# Generated by Django 4.2.7 on 2024-01-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carList', '0008_usermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='car',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='car',
            field=models.ManyToManyField(blank=True, to='carList.carmodel'),
        ),
    ]
