# Generated by Django 4.2.7 on 2023-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=255)),
                ('boolean_field', models.BooleanField()),
                ('date_time_field', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                ('integer_field', models.IntegerField()),
            ],
        ),
    ]
