# Generated by Django 4.2.7 on 2023-12-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_taskcategory_category'),
        ('task', '0003_remove_taskmodel_category_taskmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(to='category.taskcategory'),
        ),
    ]
