# Generated by Django 4.2.7 on 2023-12-18 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_taskcategory_category'),
        ('task', '0004_remove_taskmodel_category_taskmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='catName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catName_tasks', to='category.taskcategory'),
            preserve_default=False,
        ),
    ]
